#include<time.h>
#include "../../Backend/HashTableImp/Hash.h"

#include "../../Backend/Cache/Cache.h"
typedef std::vector<u_int8_t> Buffer;
class DList{
    public:
    DList* next;
    DList* prev;
};
inline void node_detach(DList* node) {
    if (node->prev) {
        node->prev->next = node->next;
    }
    if (node->next) {
        node->next->prev = node->prev;
    }
    node->next = nullptr;
    node->prev = nullptr;
}

inline void dlist_init(DList* node){
    node->prev = node->next = node;
}
inline bool dlist_empty(DList* node){
    return node->next == node;
}
static void insert_before(DList* existing_node,DList* new_node) {
    new_node->next = existing_node;
    new_node->prev = existing_node->prev;
    existing_node->prev->next = new_node;
    existing_node->prev = new_node;
}
struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming;    // data to be parsed by the application
    Buffer outgoing;    // responses generated by the application
    // timer
    u_int64_t last_active_ms = 0;
    DList idle_node;
};

// global states
static struct {
    HMap db;
    // a map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;
    // timers for idle connections
    DList idle_list;
    // timers for TTLs
    std::vector<HeapItem> heap;
} g_data;





u_int64_t getCurrentTimeMillis() {
    struct timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts) == -1) {
        std::cerr << "Error getting time" << std::endl;
        return -1; 
    }
    return static_cast<u_int64_t>(ts.tv_sec) * 1000 + ts.tv_nsec / 1000000;
}